apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd.root
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  labels:
    app.kubernetes.io/name: root
    app.kubernetes.io/component: application
    app.kubernetes.io/part-of: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  project: default
  source:
    repoURL: https://github.com/srobroek/argo-at-home.git
    path: stacks/argocd
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - PruneLast=true      
    