---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd-server-tls
  namespace: argocd
  labels:
    "solver": "dns-cloudflare"
    "acme-env": "prod"
spec:
  commonName: argocd.svc.int.vxsan.com
  dnsNames:
  - argocd.int.vxsan.com
  - argocd.vxsan.com
  - argocd.svc.int.vxsan.com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  secretName: argocd-server-tls  