apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: argo-httpproxy-svc-int
  namespace: argocd
spec:
  virtualhost:
    fqdn: argocd.svc.int.vxsan.com
    tls:
      secretName: argocd-server-tls
  routes:
  - services:
    - name: argocd-server
      port: 80
---
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: argo-httpproxy-int
  namespace: argocd
spec:
  virtualhost:
    fqdn: argocd.int.vxsan.com
    tls:
      secretName: argocd-server-tls
  routes:
  - services:
    - name: argocd-server
      port: 80
---
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: argo-httpproxy-ext
  namespace: argocd
spec:
  virtualhost:
    fqdn: argocd.vxsan.com
    tls:
      secretName: argocd-server-tls
  routes:
  - services:
    - name: argocd-server
      port: 80   