# apiVersion: projectcontour.io/v1
# kind: HTTPProxy
# metadata:
#   name: argo-httpproxy-svc-int
#   namespace: argocd
# spec:
#   virtualhost:
#     fqdn: argocd.svc.int.vxsan.com
#     tls:
#       secretName: argocd-server-tls
#   routes:
#   - services:
#     - name: argocd-server
#       port: 80
# ---
# apiVersion: projectcontour.io/v1
# kind: HTTPProxy
# metadata:
#   name: argo-httpproxy-int
#   namespace: argocd
# spec:
#   virtualhost:
#     fqdn: argocd.int.vxsan.com
#     tls:
#       secretName: argocd-server-tls
#   routes:
#   - services:
#     - name: argocd-server
#       port: 80
# ---
# apiVersion: projectcontour.io/v1
# kind: HTTPProxy
# metadata:
#   name: argo-httpproxy-ext
#   namespace: argocd
# spec:
#   virtualhost:
#     fqdn: argocd.vxsan.com
#     tls:
#       secretName: argocd-server-tls
#   routes:
#   - services:
#     - name: argocd-server
#       port: 80   

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argocd-ingress
  namespace: argocd
  annotations:
    ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  rules:
  - host: argocd.int.vxsan.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service: 
            name: argocd-server
            port:
              number: 80
  - host: argocd.vxsan.com
    http:
      paths: 
      - path: /
        pathType: Prefix
        backend:
          service:
            name: argocd-server
            port: 
              number: 80
  tls:
  - hosts:
    - argocd.int.vxsan.com
    - argocd.vxsan.com
    secretName: argocd-server-tls