---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  labels: 
    app.kubernetes.io/name: cert-manager.app
    app.kubernetes.io/component: application
    app.kubernetes.io/part-of: cert-manager
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  project: default
  source:
    repoURL: 'https://charts.jetstack.io'
    targetRevision: v1.5.3
    chart: cert-manager
    helm:
      parameters:
      - name: "installCRDs"
        value: 'true'
      values: |
        extraArgs: 
          - --dns01-recursive-nameservers-only
          - --dns01-recursive-nameservers=1.1.1.1:53,9.9.9.9:53

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - PruneLast=true
