apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: contour
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  labels:
    app.kubernetes.io/name: contour
    app.kubernetes.io/component: application
    app.kubernetes.io/part-of: infrastructure
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: contour
    targetRevision: 5.5.3
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:    
    - CreateNamespace=true 