apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  labels:
    app.kubernetes.io/name: root
    app.kubernetes.io/component: application
    app.kubernetes.io/part-of: argocd
spec:
  destination:
    server: https://kubernetes.default.svc

  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: metallb
    targetRevision: 0.10.2
    helm:
      values: |
        configInline:
          address-pools:
            - name: default
              protocol: layer2
              addresses:
              - 172.21.3.201-172.21.3.240
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:    
    - CreateNamespace=true 