---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: media-ingress-tls
  namespace: media
  labels:
    "solver": "dns-cloudflare"
    "acme-env": "prod"
spec:
  commonName: media.svc.int.vxsan.com
  dnsNames:
  - media.int.vxsan.com
  - media.vxsan.com
  - media.svc.int.vxsan.com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  secretName: media-ingress-tls  