---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prowlarr
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  labels: 
    app.kubernetes.io/name: prowlarr
    app.kubernetes.io/component: application
    app.kubernetes.io/part-of: media
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: media
  project: media
  source:
    repoURL: 'https://k8s-at-home.com/charts/'
    chart: prowlarr  
    targetRevision: v1.5.3
    helm:
      values: |
        image:
          tag: latest
        env:
          TZ: "Asia/Dubai"
        ingress:
          main:
            enabled: true
            hosts:
              host: media.int.vxsan.com
              paths:
                path: /prowlarr
                pathType: Prefix
            tls:
              - secretname: media-ingress-tls
                hosts:
                  - media.int.vxsan.com
                  - media.vxsan.comk apply -
                
        persistence:
          config:
            enabled: true
            type: pvc
            size: 1Gi

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - PruneLast=true
