apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: media.root
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  labels:
    app.kubernetes.io/name: root
    app.kubernetes.io/component: application
    app.kubernetes.io/part-of: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  project: media
  source:
    repoURL: https://github.com/srobroek/argo-at-home.git
    path: stacks/media
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
